name: Build ExpDots ISO

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Update system and install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm --needed archiso git base-devel

    - name: Setup build environment
      run: |
        # Copy package list
        cp packages.x86_64 archiso/
        
        # Create config directories
        mkdir -p archiso/airootfs/root/.config/{hypr,waybar,mako,mpd,ncmpcpp,cava}
        
        # Copy configuration files
        cp configs/hyprland.conf archiso/airootfs/root/.config/hypr/
        cp configs/waybar-config.jsonc archiso/airootfs/root/.config/waybar/config
        cp configs/mako-config archiso/airootfs/root/.config/mako/config
        cp configs/mpd.conf archiso/airootfs/root/.config/mpd/
        cp configs/ncmpcpp-config archiso/airootfs/root/.config/ncmpcpp/config
        cp configs/cava-config archiso/airootfs/root/.config/cava/config
        cp configs/starship.toml archiso/airootfs/root/.config/

    - name: Build ISO
      run: |
        cd archiso
        mkarchiso -v .

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExpDots-ISO
        path: archiso/out/*.iso
        retention-days: 7
        compression-level: 9
