name: Build ExpDots ISO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      
    steps:
    - name: Update Arch Linux
      run: |
        pacman -Syu --noconfirm --needed
        pacman -S --noconfirm --needed archiso git sudo base-devel
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup build environment
      run: |
        # Copy package list
        cp packages.x86_64 archiso/
        
        # Create directory structure
        mkdir -p archiso/airootfs/root/.config/{hypr,waybar,mako,mpd,ncmpcpp,cava}
        
        # Copy config files
        cp configs/hyprland.conf archiso/airootfs/root/.config/hypr/
        cp configs/waybar-config.jsonc archiso/airootfs/root/.config/waybar/config
        cp configs/mako-config archiso/airootfs/root/.config/mako/config
        cp configs/mpd.conf archiso/airootfs/root/.config/mpd/
        cp configs/ncmpcpp-config archiso/airootfs/root/.config/ncmpcpp/config
        cp configs/cava-config archiso/airootfs/root/.config/cava/config
        cp configs/starship.toml archiso/airootfs/root/.config/
        
    - name: Build ISO
      run: |
        cd archiso
        mkarchiso -v .
        
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExpDots-ISO
        path: archiso/out/*.iso
        retention-days: 7
