name: Build ExpDots ISO

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build ISO using Docker
      run: |
        docker run --rm \
          -v $PWD:/work \
          -w /work \
          archlinux:latest \
          bash -c "
            pacman -Syu --noconfirm
            pacman -S --noconfirm archiso
            cd archiso
            mkarchiso -v .
          "
    
    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: expdots-iso
        path: archiso/out/*.iso
